Global:
  use_gpu: True
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./svtr_large_stn
  save_epoch_step: 400
  # evaluation is run every 2000 iterations after the 0th iteration
  eval_batch_step: [0, 5000]
  cal_metric_during_train: True
  pretrained_model: 
  checkpoints: 
  save_inference_dir:
  use_visualdl: False
  infer_img: data/DDT_crop/test/
  # for data or label process
  character_dict_path: ./ppocr/utils/EN_symbol_dict.txt
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: ./svtr_large_stn.csv


Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 0.00000008
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed
  one_dim_param_no_weight_decay: true
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 10
Architecture:
  model_type: rec
  algorithm: SVTR
  Backbone:
    name: SVTRNet
    img_size:
    - 32
    - 200
    out_char_num: 40
    out_channels: 384
    patch_merging: Conv
    embed_dim:
    - 192
    - 256
    - 512
    depth:
    - 3
    - 9
    - 9
    num_heads:
    - 6
    - 8
    - 16
    mixer:
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    local_mixer:
    - - 7
      - 11
    - - 7
      - 11
    - - 7
      - 11
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead
Loss:
  name: CTCLoss
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    label_file_list:
    - ./data/train.txt
    data_dir: ./data/DDT_crop/train
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug: null
    - CTCLabelEncode: null
    - RecResizeImg:
        character_dict_path: null
        image_shape:
        - 3
        - 32
        - 200
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 20
Eval:
  dataset:
    name: SimpleDataSet
    label_file_list:
    - ./data/val.txt
    data_dir: ./data/DDT_crop/train
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: null
    - RecResizeImg:
        character_dict_path: null
        image_shape:
        - 3
        - 32
        - 200
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 64
    num_workers: 4
profiler_options: null
